volumes:
  pg_data:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5 

  backend:
    depends_on:
      db:
        condition: service_healthy 
    build:
      context: ../backend
      dockerfile: ../backend/Dockerfile
    env_file: .env


  gateway:
    build:
      context: ../gateway
      dockerfile: ../gateway/Dockerfile
    depends_on:
      - backend
    env_file: .env
    ports:
      - "8080:${AIOHTTP_PORT}"

  redis:
    image: redis:7

  